### PR TITLE
Added google-test submodule

### PR DESCRIPTION
**Pull request by Soskar1**

### CODE REVIEW

**Comment by Maksasj** [comment]
pls add some sample tests(maybe rewrite tests that we already have), just to ensure that everything works

**Comment by Maksasj** [comment]
also, would be cool to integrate it with github actions

**Review by Maksasj — COMMENTED** [review]
**comments**

**Comment by Soskar1** [comment]
OK, man!

**Comment by Maksasj** [comment]
> OK, man!

image

**Review by Maksasj — APPROVED** [review]

**Pull request merged**
